---
functional:
  - пользователь должен иметь возможноасть зарегестрироваться на сайте через электронную почту, аккаунт в Гитхабе или через Discord
  - пользователь должен иметь возможность зайти на сайт через электронную почту, аккаунт в Гитхабе или через Discord
  - пользователь должен иметь возможность создать игру с выбором параметров (уровень, тип игры, время)
  - после создания игра должна быть доступна для выбранного соперника или других пользлвателей исходя из выбранной опции
  - пользователь должен иметь возможность присоединиться к игре созданной другим пользователем
  - пользователь должен иметь возможность выбрать язык программирования в игре
  - пользователь должен иметь возможность писать в чат игры
  - пользователь должен иметь возможность переподключиться к игре, если он вылетел из игры
non-functional:
  - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен быть удобным на мобильном устройстве
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - пользователь должен иметь возможность просматривать рейтинг пользователей
  - пользователь должен иметь возможность выставлять в настройках нужный ему язык программирования по умолчанию